apiVersion: v1
kind: Service
metadata:
  name: envoy
  namespace: temp-converter-grpc
  labels:
    app: envoy
spec:
  # NodePort for Ingress (GCE Ingress requires NodePort or LoadBalancer backends)
  type: NodePort
  selector:
    app: envoy
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
